### ISSUE TITLE
Video Record

### ISSUE THREAD

**Issue by LucaUssi** [multipath-rtp/gst-mprtp#2]
Hi,
I have a question to do.
Can I record the file that the Client receive when I use the "YUVFILE_SOURCE" profile?
I tried replacing the "autovideosink" element, in the Client code, with the "filesink" element but it not work.
The recorded video is different from the video that I receive.
Best regards,
                  Luca Ussi

**Comment by balazskreith** [comment]
Hi Luca,

Probably you can. Lets see if it is an mprtp issue! 
Try record it by using only one subflow and see if the problem remains. If it exists with only one subflow then we need to change the pipeline.

**Comment by LucaUssi** [comment]
Hi Balázs,
I've tried to record the video by using only one subflow, but it doesn’t work. When I send my yuv file from Server to Client and and if I use "autovideosink", the video is correctly visualized. Otherwise, if I use "filesink" instead of autovideosink, the recorded video has some missing parts, instead of the source video.
Best regards.

**Comment by balazskreith** [comment]
mprtp plugin at the receiver side passes the rtp packets towards intactly. It only retain them to join packets originated from different subflows. That retain and playout distortion causes your problem in visualization probably causes by the different delays. I am experimenting some playout algorithms for proper joins. Some gives better results even if the delays are highly different, but usually they have problems if pathes becoming congested. if we use only one subflow, packets are just goes towards with slightly delay. So shortly I think you need a gstelement before you save the output into a file. 
You can tryout or see how it goes with rtp by checking some examples here:
https://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/tests/examples/rtp

Although I will check it also a little bit later, perhaps I forget to react some events or queries necessary for saving but not for visualizing.

**Comment by balazskreith** [comment]
One more thing!
I recommend you to run your gstreamer pipeline with GST_DEBUG=X. You can do this with mprtp by entering into ns_snd or ns_rcv namespace bash by giving the sudo ip netns exec ns_rcv bash command.
Then you can run the client at ns_rcv by giving: GST_DEBUG=3 ./client --profile=X. 3 means you will get warning messages from gstreamer elements. 

For more information about gst_debug see this: http://docs.gstreamer.com/display/GstSDK/Basic+tutorial+11%3A+Debugging+tools 

Gstreamer warnings and errors may help you to identify the problem.

**Comment by LucaUssi** [comment]
Hi Balázs,
I've noticed that the received video is different from the one sent because when the Client begin to record using the "filesink" element, the Server has sent a part of the video yet.  In this way I miss always the first part of the video. 
These are the Client side pipeline and the Server side pipeline:
Client:  queue->rtpvp8depay->vp8dec->filesink
Server 
Can I delay the server transmission?
 Best regards.

**Comment by LucaUssi** [comment]
I'm Sorry, this is the Server side pipeline:
Server: multifilesrc->identity->videoparse->rtpvp8pay->vp8enc

**Comment by balazskreith** [comment]
Hi Luca,

You can start the client first then wait a second (or 2) and run the server. I did the other way around in scripts, and thats not good. I changed the order of start at run_stest so you can pull it down. Notify me if it works, also you can increase a sleep between the client and server start by editing run_stest.

**Comment by LucaUssi** [comment]
Hi Balázs,
I’ve tried in this way but it doesn’t work.
The problem is that the client print “Linked!” but there are some second of pause before the Client's pipeline changed state from PAUSED to PLAYING.
This pause time increase if I increase the numbers of active subflows.
Best regards.

**Comment by balazskreith** [comment]
You can force a retainment at the receiver side by set mprtpplayouter's  "halt-time" object property. It forces the playoutqueue to retain buffers for specific amount of time. That time is equal to _now_ + _halt_time_ in milliseconds, where _now_ is the time when you set the halt_time property.

In code its like this:
g_object_set (mprtpplayouter, "halt-time", 5000, NULL); 
and it retains your buffer for 5s before it starts to pass it towards.

If it doesn't work, then we will see where and what needs to be implement.

**Comment by LucaUssi** [comment]
Hi Balázs,
I've tried to use
g_object_set (mprtpplayouter, "halt-time", 5000, NULL);
but it doesn't work yet. I don't see the first part of the video sent yet.
Best regards.

**Comment by balazskreith** [comment]
Hi Luca,

Okay, then its need to be investigated. I don't think that build a halt-time at the server side would be an appropriate solution, I think I need to revise the events and segments at the client side, but I need to finish a development ongoing now.

If you need an urgent solution, then change the method [_mprtpscheduler_process_run](https://github.com/multipath-rtp/gst-mprtp/blob/master/plugins/gstmprtpscheduler.c#L1047) at [plugins/gstmprtpscheduler](https://github.com/multipath-rtp/gst-mprtp/blob/master/plugins/gstmprtpscheduler.c) and change the _next_scheduler_time_ local variable to a different value to apply a delay, but change it back to 1ms after your time has expired.
